name: Build and push the image to the registry with tags
on: 
  push:
    tags:
      - '*'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - 
                uses: actions/checkout@v4
                name: Checkout
            -   
                name: Setup QEMU
                uses: docker/setup-qemu-action@v3.0.0
            -
                name: Docker meta
                id: docker_meta
                uses: docker/metadata-action@v5
                with:
                    images: |
                        cheetahfox/ipmi-api
                    tags: |
                        type=ref,event=branch
                        type=ref,event=pr
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}.{{minor}}.{{patch}}
            -
                name: Login to the registry
                uses: docker/login-action@v3.0.0
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v5
                with:
                    context: "{{defaultContext}}"
                    push: true
                    tags: ${{ steps.docker_meta.outputs.tags}}
                    labels: ${{ steps.docker_meta.outputs.labels}}